In [1]:
##Importation des bibliothèques nécessaires
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
import joblib

In [2]:
# 1. Chargement des données 
data=pd.read_csv("../data/donnees_dpe_rhone_clean.csv",delimiter=",")

In [3]:
pd.set_option('display.max_columns', None)  # Affiche toutes les colonnes
data.head(3)

configuration_installation_chauffage_n2  \
0        Installation de chauffage simple   
1        Installation de chauffage simple   
2        Installation de chauffage simple   

  configuration_installation_chauffage_n1  \
0        Installation de chauffage simple   
1        Installation de chauffage simple   
2        Installation de chauffage simple   

   conso_chauffage_installation_chauffage_n1  \
0                                    25718.3   
1                                    25718.3   
2                                    14399.6   

            type_generateur_n1_ecs_n1  numero_voie_ban  score_ban  \
0  Chaudière bois granulés après 2019           1147.0       0.37   
1  Chaudière bois granulés après 2019           1147.0       0.37   
2  Chaudière bois granulés après 2019            299.0       0.45   

   conso_chauffage_generateur_n1_installation_n2  conso_auxiliaires_ep  \
0                                         5987.3                 710.9   
1                                         5987.3                 710.9   
2                                         2528.6                 538.4   

   conso_chauffage_installation_chauffage_n2  deperditions_murs  \
0                                     5987.3              155.8   
1                                     5987.3              155.8   
2                                     2528.6               59.3   

   cout_eclairage  conso_auxiliaires_ef                  statut_geocodage  \
0            68.3                 309.1  adresse géocodée ban à l'adresse   
1            68.3                 309.1  adresse géocodée ban à l'adresse   
2            76.5                 234.1  adresse géocodée ban à l'adresse   

   ventilation_posterieure_2012  cout_chauffage  conso_ecs_ef_energie_n3  \
0                             0          1732.4                      0.0   
1                             0          1732.4                      0.0   
2                             0          1287.8                      0.0   

   conso_5_usages_par_m2_ep date_etablissement_dpe  conso_ecs_ef_energie_n1  \
0                     282.0             2024-06-23                   2803.0   
1                     282.0             2024-06-23                   2803.0   
2                     168.0             2024-07-07                   4511.9   

   conso_ecs_ef_energie_n2  emission_ges_chauffage  \
0                      0.0                   951.2   
1                      0.0                   951.2   
2                      0.0                   638.3   

               description_installation_chauffage_n2  \
0  Poêle à bois (bûche) installé de 2005 à 2006 a...   
1  Poêle à bois (bûche) installé de 2005 à 2006 a...   
2  Poêle à granulés flamme verte installé entre 2...   

               description_installation_chauffage_n1  \
0  Chaudière individuelle bois (granulés) install...   
1  Chaudière individuelle bois (granulés) install...   
2  Chaudière individuelle bois (granulés) install...   

  qualite_isolation_plancher_haut_comble_amenage  conso_5_usages_par_m2_ef  \
0                                          bonne                     276.0   
1                                          bonne                     276.0   
2                                            NaN                     150.0   

   cout_ecs_energie_n2  conso_chauffage_ef_energie_n1  cout_ecs_energie_n3  \
0                  0.0                        25718.3                  0.0   
1                  0.0                        25718.3                  0.0   
2                  0.0                        14399.6                  0.0   

   conso_chauffage_ef_energie_n2  presence_brasseur_air  \
0                         5987.3                    0.0   
1                         5987.3                    0.0   
2                         2528.6                    0.0   

  qualite_isolation_menuiseries  conso_chauffage_ef_energie_n3  \
0                  insuffisante                            0.0   
1          

In [4]:
# Supposons que la colonne cible est "Etiquette_DPE" et qu'il y a des colonnes catégorielles et numériques
target = 'etiquette_dpe'
data = data.dropna(subset=[target])

In [5]:
ls_variables_explicatives = [
    'conso_5_usages_par_m2_ep',
    'emission_ges_5_usages_par_m2',
    'conso_5_usages_par_m2_ef',
    'conso_chauffage_ep',
    'emission_ges_chauffage',
    'cout_chauffage',
    'besoin_ecs',
    'surface_habitable_logement',
    'cout_total_5_usages',
    'conso_5_usages_ef_energie_n1',
    'conso_ecs_ep',
    'conso_eclairage_ef',
    'type_energie_principale_chauffage',
    'conso_chauffage_ef',
    'annee_construction'
]


In [6]:
# Définir les données d'entrée et la variable cible
X = data[ls_variables_explicatives]
y = data[target]


In [7]:
X.head(3)

conso_5_usages_par_m2_ep  emission_ges_5_usages_par_m2  \
0                     282.0                           8.0   
1                     282.0                           8.0   
2                     168.0                           5.0   

   conso_5_usages_par_m2_ef  conso_chauffage_ep  emission_ges_chauffage  \
0                     276.0             31705.6                   951.2   
1                     276.0             31705.6                   951.2   
2                     150.0             20725.5                   638.3   

   cout_chauffage  besoin_ecs  surface_habitable_logement  \
0          1732.4      1499.7                       126.6   
1          1732.4      1499.7                       126.6   
2          1287.8      1657.2                       157.0   

   cout_total_5_usages  conso_5_usages_ef_energie_n1  conso_ecs_ep  \
0               2058.3                       28521.3        2803.0   
1               2058.3                       28521.3        2803.0   
2               1615.2                       18911.5        4511.9   

   conso_eclairage_ef        type_energie_principale_chauffage  \
0               235.4  Bois – Granulés (pellets) ou briquettes   
1               235.4  Bois – Granulés (pellets) ou briquettes   
2               292.0                            Bois – Bûches   

   conso_chauffage_ef  annee_construction  
0             31705.6                1948  
1             31705.6                1948  
2             18579.2                1948

In [8]:
y.head(3)

0    E
1    E
2    C
Name: etiquette_dpe, dtype: object

In [9]:
# Séparer les colonnes numériques et catégorielles
numeric_features = data[ls_variables_explicatives].select_dtypes(include=[np.number]).columns
categorical_features = data[ls_variables_explicatives].select_dtypes(exclude=[np.number]).columns

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# Création des transformations pour chaque type de données
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),      # Impute les valeurs manquantes par la mediane
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Impute les valeurs manquantes par la valeur la plus fréquente
    ('ordinal', OrdinalEncoder())  # Encodage des variables catégorielles
])


# Application des transformations
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 4. Création du pipeline complet
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, min_samples_split=5, random_state=0, verbose=1))
])

In [12]:
#Entraînement du modèle
pipeline.fit(X_train, y_train)


[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    5.3s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   11.5s finished


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['conso_5_usages_par_m2_ep', 'emission_ges_5_usages_par_m2',
       'conso_5_usages_par_m2_ef', 'conso_chauffage_ep',
       'emission_ges_chauffage', 'cout_chauffage', 'besoin_ecs',
       'surface_habitable_logement', 'cout_total_5_usages',
       'conso_5_usages_ef_energie_n1', 'conso_ecs_ep', 'conso_eclairage_ef',
       'conso_chauffage_ef', 'annee_construction'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder())]),
                                                  Index(['type_energie_principale_chauffage'], dtype='object'))])),
                ('classifier',
                 RandomForestClassifier(min_samples_split=5, random_state=0,
                                        verbose=1))])

In [14]:
# 5️⃣ Sauvegarder le pipeline dans un fichier .pkl
joblib.dump(pipeline, '../Modèle/pipeline.pkl')

['../Modèle/pipeline.pkl']

In [15]:
rf_y_pred = pipeline.predict(X_test)
rf_y_pred

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.3s finished


array(['D', 'G', 'E', ..., 'E', 'E', 'G'], dtype=object)

In [16]:
#Évaluation du modèle
print("Matrice de confusion :\n", confusion_matrix(y_test, rf_y_pred))
print("Rapport de classification :\n", classification_report(y_test, rf_y_pred))

Matrice de confusion :
 [[  600     0     0     0     0     0]
 [    0  1836     0     0     0     0]
 [    0     0 12097     0     0     0]
 [    0     0     0 15486     0     0]
 [    0     0     0     0  9670     0]
 [    0     0     0     0     0 11652]]
Rapport de classification :
               precision    recall  f1-score   support

           B       1.00      1.00      1.00       600
           C       1.00      1.00      1.00      1836
           D       1.00      1.00      1.00     12097
           E       1.00      1.00      1.00     15486
           F       1.00      1.00      1.00      9670
           G       1.00      1.00      1.00     11652

    accuracy                           1.00     51341
   macro avg       1.00      1.00      1.00     51341
weighted avg       1.00      1.00      1.00     51341



In [17]:
# Chargement et utilisation du pipeline sauvegardé
pipeline_loaded = joblib.load('../Modèle/pipeline.pkl')

In [18]:
y_pred_loaded = pipeline_loaded.predict(X_test)
print("Évaluation du pipeline chargé :")
print("Matrice de confusion :\n", confusion_matrix(y_test, y_pred_loaded))
print("Rapport de classification :\n", classification_report(y_test, y_pred_loaded))

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.5s finished


Évaluation du pipeline chargé :
Matrice de confusion :
 [[  600     0     0     0     0     0]
 [    0  1836     0     0     0     0]
 [    0     0 12097     0     0     0]
 [    0     0     0 15486     0     0]
 [    0     0     0     0  9670     0]
 [    0     0     0     0     0 11652]]
Rapport de classification :
               precision    recall  f1-score   support

           B       1.00      1.00      1.00       600
           C       1.00      1.00      1.00      1836
           D       1.00      1.00      1.00     12097
           E       1.00      1.00      1.00     15486
           F       1.00      1.00      1.00      9670
           G       1.00      1.00      1.00     11652

    accuracy                           1.00     51341
   macro avg       1.00      1.00      1.00     51341
weighted avg       1.00      1.00      1.00     51341

